"""empty message

Revision ID: 7c98e1f59f3f
Revises: e7908f214fa8
Create Date: 2023-03-10 21:56:02.809597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c98e1f59f3f'
down_revision = 'e7908f214fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('Is deleted?')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('Is deleted?')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Is deleted?')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Is deleted?', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Is deleted?', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Is deleted?', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
